const WATER_AMOUNT_DEFAULT = 100;
const WATER_NOTIFICATION_TIME_DEFAULT = 30;
const SHOULD_NOTIFY_DEFAULT = true;

export const DefaultSettings = {
  WATER_AMOUNT_DEFAULT,
  WATER_NOTIFICATION_TIME_DEFAULT,
  SHOULD_NOTIFY_DEFAULT
};
